config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'tiles#index'

  resources :tiles

end

app/models/tile.rb
class Tile < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/tiles_controller.rb
class TilesController < ApplicationController
  before_action :set_tile, only: [:show, :edit, :update, :destroy]

  # GET /tiles
  # GET /tiles.json
  def index
    @tiles = Tile.all
  end

  # GET /tiles/1
  # GET /tiles/1.json
  def show
  end

  # GET /tiles/new
  def new
    @tile = Tile.new
  end

  # GET /tiles/1/edit
  def edit
  end

  # POST /tiles
  # POST /tiles.json
  def create
    @tile = Tile.new(tile_params)

    respond_to do |format|
      if @tile.save
        format.html { redirect_to @tile, notice: 'Tile was successfully created.' }
        format.json { render :show, status: :created, location: @tile }
      else
        format.html { render :new }
        format.json { render json: @tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tiles/1
  # PATCH/PUT /tiles/1.json
  def update
    respond_to do |format|
      if @tile.update(tile_params)
        format.html { redirect_to @tile, notice: 'Tile was successfully updated.' }
        format.json { render :show, status: :ok, location: @tile }
      else
        format.html { render :edit }
        format.json { render json: @tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tiles/1
  # DELETE /tiles/1.json
  def destroy
    @tile.destroy
    respond_to do |format|
      format.html { redirect_to tiles_url, notice: 'Tile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tile
      @tile = Tile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tile_params
      params.require(:tile).permit(:name, :item_code, :weight, :retail_price, :resell_price, :wholesale_price, :dealer_price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tiles_helper.rb
module TilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snap App</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Snap App</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Updates Blog"%></li>
            <li><%= link_to "Get Weights" %></li>
            <li><%= link_to "Freight Quote" %></li>
            <li><%= link_to "Report a Problem" %></li>
            <div>
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
            </div>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="span8"><%= yield %></div>
      <div class="span4">
        <h2>About The App</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
    </div>
  </div>
</body>
</html>

app/views/tiles/_form.html.erb
<%= form_for @tile, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :item_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :item_code, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :weight, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :weight, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :retail_price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :retail_price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :resell_price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :resell_price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :wholesale_price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :wholesale_price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :dealer_price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :dealer_price, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tiles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tiles/edit.html.erb
<%- model_class = Tile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tiles/index.html.erb
<%- model_class = Tile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:item_code) %></th>
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:retail_price) %></th>
      <th><%= model_class.human_attribute_name(:resell_price) %></th>
      <th><%= model_class.human_attribute_name(:wholesale_price) %></th>
      <th><%= model_class.human_attribute_name(:dealer_price) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tiles.each do |tile| %>
      <tr>
        <td><%= link_to tile.id, tile_path(tile) %></td>
        <td><%= tile.name %></td>
        <td><%= tile.item_code %></td>
        <td><%= tile.weight %>&nbsp; lbs</td>
        <td><%= number_to_currency(tile.retail_price) %></td>
        <td><%= number_to_currency(tile.resell_price) %></td>
        <td><%= number_to_currency(tile.wholesale_price) %></td>
        <td><%= number_to_currency(tile.dealer_price) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tile_path(tile), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tile_path(tile),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tile_path,
            :class => 'btn btn-primary' %>

app/views/tiles/new.html.erb
<%- model_class = Tile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tiles/show.html.erb
<%- model_class = Tile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @tile.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:item_code) %>:</strong></dt>
  <dd><%= @tile.item_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @tile.weight %></dd>
  <dt><strong><%= model_class.human_attribute_name(:retail_price) %>:</strong></dt>
  <dd><%= @tile.retail_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:resell_price) %>:</strong></dt>
  <dd><%= @tile.resell_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:wholesale_price) %>:</strong></dt>
  <dd><%= @tile.wholesale_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dealer_price) %>:</strong></dt>
  <dd><%= @tile.dealer_price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tiles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tile_path(@tile), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tile_path(@tile),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>